Add support for OTel Java runtime metrics
DataDog/opentelemetry-mapping-go pull request #19
Opened 2023-03-03 19:27 UTC by liustanley

### What does this PR do?

Adds mappings for Java runtime metrics and refactors the runtimeMetricMapping type to remove the metricType field. This behavior was causing errors because some runtime metrics didn't have the same type as their documentation, so I changed it to use the incoming metric type instead.

2023-03-06 15:36 UTC, liustanley commented on pkg/otlp/metrics/metrics_translator.go
> +	"process.runtime.jvm.threads.count": {{mappedName: "jvm.thread_count"}},
Sure, should we move the mappings to a new file since they're getting kind of large?

2023-03-15 21:09 UTC, dineshg13 requested changes
Can we also add GC metrics ? 
![image](https://user-images.githubusercontent.com/2471669/225443501-7aef45ec-018f-4ac8-8a4a-548d7e0de5de.png)


https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/6964/files#diff-bb4826b5d07256ae1befe69927b73586a37da8bb6dcdfa30a3ba18e5c828b55b

2023-04-10 15:21 UTC, dineshg13 commented on pkg/otlp/metrics/runtime_metric_mappings.go
> +var goRuntimeMetricsMappings = map[string][]runtimeMetricMapping{
Every runtime mapping should follow this silent contract - `map[string][]runtimeMetricMapping` --- Can we create this as a try or interface ?

2023-04-10 15:27 UTC, dineshg13 approved these changes
Looks good. Added a small comment

2023-04-12 20:14 UTC, merged

2023-11-16 14:23 UTC, sirianni commented
The aliasing of `process.runtime.jvm.gc.duration` to `jvm.gc.parnew.time` breaks setups that have both legacy Java apps using JMX and new Java applications using OTel due to a incompatibility in metric type (`distribution` vs. `gauge`).

In these scenarios, the `jvm.gc.parnew.time` metric metadata on the Datadog backend gets changed from a `gauge` to a `distribution` which causes the JMX-fetched gauge variant of `jvm.gc.parnew.time` to be completely unqueryable (disappears from all dashboards and monitors).

2023-11-16 17:00 UTC, mx-psi commented
@sirianni can you file a support ticket for this? Please share the case number here and I can loop in the relevant people :)

2023-11-16 17:41 UTC, sirianni commented
> Please share the case number here and I can loop in the relevant people :)

https://help.datadoghq.com/hc/en-us/requests/1434627